name: Deploy to Pages

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "README.md"
      - "readme.md"
  workflow_dispatch:

jobs:
  deploy:
    uses: uukelele-scratch/repo2static/.github/workflows/deploy.yml@main
